<?php

use Migrations\AbstractSeed;

/**
 * Manatypes and Skills seed.
 */
class ManatypesAndSkillsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $data = [
            [
                'id' => '1',
                'name' => 'Elemental',
            ],
            [
                'id' => '2',
                'name' => 'Spiritual',
            ],
            [
                'id' => '3',
                'name' => 'Healing',
            ],
            [
                'id' => '4',
                'name' => 'Elemental Ritual',
            ],
            [
                'id' => '5',
                'name' => 'Spiritual Ritual',
            ],
            [
                'id' => '6',
                'name' => 'Special',
            ],
        ];

        $table = $this->table('manatypes');
        $table->insert($data)->save();

        $data = [
            [
                'id' => '1',
                'name' => 'ambidextrie',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '1',
                'deprecated' => '0',
            ],
            [
                'id' => '2',
                'name' => 'levenskracht',
                'cost' => '4',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '1',
                'deprecated' => '0',
            ],
            [
                'id' => '3',
                'name' => 'lezen',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '1',
                'deprecated' => '0',
            ],
            [
                'id' => '4',
                'name' => 'rekenen',
                'cost' => '0',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '1',
                'deprecated' => '0',
            ],
            [
                'id' => '5',
                'name' => 'genezer A',
                'cost' => '4',
                'manatype_id' => '3',
                'mana_amount' => '5',
                'sort_order' => '2',
                'deprecated' => '0',
            ],
            [
                'id' => '6',
                'name' => 'genezer A t/m B',
                'cost' => '8',
                'manatype_id' => '3',
                'mana_amount' => '10',
                'sort_order' => '2',
                'deprecated' => '0',
            ],
            [
                'id' => '7',
                'name' => 'ehbg',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '3',
                'deprecated' => '0',
            ],
            [
                'id' => '8',
                'name' => 'herken bijzonder voorwerp (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '4',
                'deprecated' => '0',
            ],
            [
                'id' => '9',
                'name' => 'kennis van kruiden (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '4',
                'deprecated' => '0',
            ],
            [
                'id' => '10',
                'name' => 'kennis van drankjes (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '5',
                'deprecated' => '0',
            ],
            [
                'id' => '11',
                'name' => 'kennis van giffen (lore)',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '5',
                'deprecated' => '0',
            ],
            [
                'id' => '12',
                'name' => 'kruiden brouwen (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '5',
                'deprecated' => '0',
            ],
            [
                'id' => '13',
                'name' => 'magier A',
                'cost' => '4',
                'manatype_id' => '1',
                'mana_amount' => '5',
                'sort_order' => '6',
                'deprecated' => '0',
            ],
            [
                'id' => '14',
                'name' => 'magier A t/m B',
                'cost' => '8',
                'manatype_id' => '1',
                'mana_amount' => '10',
                'sort_order' => '6',
                'deprecated' => '0',
            ],
            [
                'id' => '15',
                'name' => 'magier A t/m C',
                'cost' => '12',
                'manatype_id' => '1',
                'mana_amount' => '15',
                'sort_order' => '6',
                'deprecated' => '0',
            ],
            [
                'id' => '16',
                'name' => 'glyphs gebruiken (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '7',
                'deprecated' => '0',
            ],
            [
                'id' => '17',
                'name' => 'bepantsering licht',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '8',
                'deprecated' => '0',
            ],
            [
                'id' => '18',
                'name' => 'bepantsering t/m halfzwaar',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '8',
                'deprecated' => '0',
            ],
            [
                'id' => '19',
                'name' => 'bepantsering t/m zwaar',
                'cost' => '4',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '8',
                'deprecated' => '0',
            ],
            [
                'id' => '20',
                'name' => 'schilden',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '8',
                'deprecated' => '0',
            ],
            [
                'id' => '21',
                'name' => 'priester A',
                'cost' => '4',
                'manatype_id' => '2',
                'mana_amount' => '5',
                'sort_order' => '9',
                'deprecated' => '0',
            ],
            [
                'id' => '22',
                'name' => 'priester A t/m B',
                'cost' => '8',
                'manatype_id' => '2',
                'mana_amount' => '10',
                'sort_order' => '9',
                'deprecated' => '0',
            ],
            [
                'id' => '23',
                'name' => 'priester A t/m C',
                'cost' => '12',
                'manatype_id' => '2',
                'mana_amount' => '15',
                'sort_order' => '9',
                'deprecated' => '0',
            ],
            [
                'id' => '24',
                'name' => 'runen gebruiken (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '10',
                'deprecated' => '0',
            ],
            [
                'id' => '25',
                'name' => 'elementair ritualist 1',
                'cost' => '1',
                'manatype_id' => '4',
                'mana_amount' => '2',
                'sort_order' => '11',
                'deprecated' => '0',
            ],
            [
                'id' => '26',
                'name' => 'elementair ritualist 2',
                'cost' => '2',
                'manatype_id' => '4',
                'mana_amount' => '4',
                'sort_order' => '11',
                'deprecated' => '0',
            ],
            [
                'id' => '27',
                'name' => 'elementair ritualist 3',
                'cost' => '3',
                'manatype_id' => '4',
                'mana_amount' => '6',
                'sort_order' => '11',
                'deprecated' => '0',
            ],
            [
                'id' => '28',
                'name' => 'elementair ritualist 4',
                'cost' => '4',
                'manatype_id' => '4',
                'mana_amount' => '8',
                'sort_order' => '11',
                'deprecated' => '0',
            ],
            [
                'id' => '29',
                'name' => 'elementair ritualist 5',
                'cost' => '5',
                'manatype_id' => '4',
                'mana_amount' => '10',
                'sort_order' => '11',
                'deprecated' => '0',
            ],
            [
                'id' => '30',
                'name' => 'elementair ritualist 6',
                'cost' => '6',
                'manatype_id' => '4',
                'mana_amount' => '12',
                'sort_order' => '11',
                'deprecated' => '0',
            ],
            [
                'id' => '31',
                'name' => 'elementair ritualist 7',
                'cost' => '7',
                'manatype_id' => '4',
                'mana_amount' => '14',
                'sort_order' => '11',
                'deprecated' => '0',
            ],
            [
                'id' => '32',
                'name' => 'spiritueel ritualist 1',
                'cost' => '1',
                'manatype_id' => '5',
                'mana_amount' => '2',
                'sort_order' => '12',
                'deprecated' => '0',
            ],
            [
                'id' => '33',
                'name' => 'spiritueel ritualist 2',
                'cost' => '2',
                'manatype_id' => '5',
                'mana_amount' => '4',
                'sort_order' => '12',
                'deprecated' => '0',
            ],
            [
                'id' => '34',
                'name' => 'spiritueel ritualist 3',
                'cost' => '3',
                'manatype_id' => '5',
                'mana_amount' => '6',
                'sort_order' => '12',
                'deprecated' => '0',
            ],
            [
                'id' => '35',
                'name' => 'spiritueel ritualist 4',
                'cost' => '4',
                'manatype_id' => '5',
                'mana_amount' => '8',
                'sort_order' => '12',
                'deprecated' => '0',
            ],
            [
                'id' => '36',
                'name' => 'spiritueel ritualist 5',
                'cost' => '5',
                'manatype_id' => '5',
                'mana_amount' => '10',
                'sort_order' => '12',
                'deprecated' => '0',
            ],
            [
                'id' => '37',
                'name' => 'spiritueel ritualist 6',
                'cost' => '6',
                'manatype_id' => '5',
                'mana_amount' => '12',
                'sort_order' => '12',
                'deprecated' => '0',
            ],
            [
                'id' => '38',
                'name' => 'spiritueel ritualist 7',
                'cost' => '7',
                'manatype_id' => '5',
                'mana_amount' => '14',
                'sort_order' => '12',
                'deprecated' => '0',
            ],
            [
                'id' => '39',
                'name' => 'kleine wapens',
                'cost' => '0',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '13',
                'deprecated' => '0',
            ],
            [
                'id' => '40',
                'name' => '1-handige wapens',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '14',
                'deprecated' => '0',
            ],
            [
                'id' => '41',
                'name' => '2-handige wapens',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '14',
                'deprecated' => '0',
            ],
            [
                'id' => '42',
                'name' => 'stafwapens',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '14',
                'deprecated' => '0',
            ],
            [
                'id' => '43',
                'name' => 'werpwapens',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '14',
                'deprecated' => '0',
            ],
            [
                'id' => '44',
                'name' => 'boogschieten',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '15',
                'deprecated' => '0',
            ],
            [
                'id' => '45',
                'name' => 'beschermende drankjes brouwen (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '46',
                'name' => 'foerageren',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '47',
                'name' => 'geestbeïnvloedende drankjes en giffen brouwen (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '48',
                'name' => 'genezende drankjes brouwen (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '49',
                'name' => 'giffen aanbrengen  (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '50',
                'name' => 'giffen brouwen (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '51',
                'name' => 'kruiden bewaren (blanks)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '52',
                'name' => 'magische drankjes brouwen A (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '53',
                'name' => 'magische drankjes brouwen B (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '54',
                'name' => 'wapengiffen brouwen A (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '55',
                'name' => 'wapengiffen brouwen B (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '20',
                'deprecated' => '0',
            ],
            [
                'id' => '56',
                'name' => 'demonologie A (genezer)',
                'cost' => '4',
                'manatype_id' => '3',
                'mana_amount' => '5',
                'sort_order' => '30',
                'deprecated' => '0',
            ],
            [
                'id' => '57',
                'name' => 'demonologie A t/m B (genezer)',
                'cost' => '8',
                'manatype_id' => '3',
                'mana_amount' => '10',
                'sort_order' => '30',
                'deprecated' => '0',
            ],
            [
                'id' => '58',
                'name' => 'demonologie A (magiër)',
                'cost' => '4',
                'manatype_id' => '1',
                'mana_amount' => '5',
                'sort_order' => '31',
                'deprecated' => '0',
            ],
            [
                'id' => '59',
                'name' => 'demonologie A t/m B (magiër)',
                'cost' => '8',
                'manatype_id' => '1',
                'mana_amount' => '10',
                'sort_order' => '31',
                'deprecated' => '0',
            ],
            [
                'id' => '60',
                'name' => 'demonologie A (priester)',
                'cost' => '4',
                'manatype_id' => '2',
                'mana_amount' => '5',
                'sort_order' => '32',
                'deprecated' => '0',
            ],
            [
                'id' => '61',
                'name' => 'demonologie A t/m B (priester)',
                'cost' => '8',
                'manatype_id' => '2',
                'mana_amount' => '10',
                'sort_order' => '32',
                'deprecated' => '0',
            ],
            [
                'id' => '62',
                'name' => 'uitdrijving',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '33',
                'deprecated' => '0',
            ],
            [
                'id' => '63',
                'name' => 'vernietig servitar',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '33',
                'deprecated' => '0',
            ],
            [
                'id' => '64',
                'name' => 'druidisme - leven',
                'cost' => '4',
                'manatype_id' => '6',
                'mana_amount' => '5',
                'sort_order' => '40',
                'deprecated' => '0',
            ],
            [
                'id' => '65',
                'name' => 'druidisme - dood',
                'cost' => '4',
                'manatype_id' => '6',
                'mana_amount' => '5',
                'sort_order' => '41',
                'deprecated' => '0',
            ],
            [
                'id' => '66',
                'name' => 'magiër A (druid)',
                'cost' => '4',
                'manatype_id' => '6',
                'mana_amount' => '5',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '67',
                'name' => 'magiër A t/m B (druid)',
                'cost' => '8',
                'manatype_id' => '6',
                'mana_amount' => '10',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '68',
                'name' => 'magiër A t/m C (druid)',
                'cost' => '12',
                'manatype_id' => '6',
                'mana_amount' => '15',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '69',
                'name' => 'magiër A t/m D (druid)',
                'cost' => '16',
                'manatype_id' => '6',
                'mana_amount' => '20',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '70',
                'name' => 'magiër A t/m E (druid)',
                'cost' => '20',
                'manatype_id' => '6',
                'mana_amount' => '25',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '71',
                'name' => 'priester A (druid)',
                'cost' => '4',
                'manatype_id' => '6',
                'mana_amount' => '5',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '72',
                'name' => 'priester A t/m B (druid)',
                'cost' => '8',
                'manatype_id' => '6',
                'mana_amount' => '10',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '73',
                'name' => 'priester A t/m C (druid)',
                'cost' => '12',
                'manatype_id' => '6',
                'mana_amount' => '15',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '74',
                'name' => 'priester A t/m D (druid)',
                'cost' => '16',
                'manatype_id' => '6',
                'mana_amount' => '20',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '75',
                'name' => 'priester A t/m E (druid)',
                'cost' => '20',
                'manatype_id' => '6',
                'mana_amount' => '25',
                'sort_order' => '42',
                'deprecated' => '0',
            ],
            [
                'id' => '76',
                'name' => 'bloedwede',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '43',
                'deprecated' => '0',
            ],
            [
                'id' => '77',
                'name' => 'grove meester',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '43',
                'deprecated' => '0',
            ],
            [
                'id' => '78',
                'name' => 'roep van de grove',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '43',
                'deprecated' => '0',
            ],
            [
                'id' => '79',
                'name' => 'genezer A t/m C',
                'cost' => '12',
                'manatype_id' => '3',
                'mana_amount' => '15',
                'sort_order' => '50',
                'deprecated' => '0',
            ],
            [
                'id' => '80',
                'name' => 'genezer A t/m D',
                'cost' => '16',
                'manatype_id' => '3',
                'mana_amount' => '20',
                'sort_order' => '50',
                'deprecated' => '0',
            ],
            [
                'id' => '81',
                'name' => 'genees andere wezens',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '51',
                'deprecated' => '0',
            ],
            [
                'id' => '82',
                'name' => 'genezer van geest',
                'cost' => '4',
                'manatype_id' => '3',
                'mana_amount' => '5',
                'sort_order' => '51',
                'deprecated' => '0',
            ],
            [
                'id' => '83',
                'name' => 'immuun voor giffen',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '51',
                'deprecated' => '0',
            ],
            [
                'id' => '84',
                'name' => 'immuun voor ziekte',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '51',
                'deprecated' => '0',
            ],
            [
                'id' => '85',
                'name' => 'levensgift',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '51',
                'deprecated' => '0',
            ],
            [
                'id' => '86',
                'name' => 'boekbinder (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '60',
                'deprecated' => '0',
            ],
            [
                'id' => '87',
                'name' => 'houtwerker (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '60',
                'deprecated' => '0',
            ],
            [
                'id' => '88',
                'name' => 'juwelier (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '60',
                'deprecated' => '0',
            ],
            [
                'id' => '89',
                'name' => 'kleermaker/leerlooier (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '60',
                'deprecated' => '0',
            ],
            [
                'id' => '90',
                'name' => 'pantsersmid (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '60',
                'deprecated' => '0',
            ],
            [
                'id' => '91',
                'name' => 'smid (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '60',
                'deprecated' => '0',
            ],
            [
                'id' => '92',
                'name' => 'wapensmid (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '60',
                'deprecated' => '0',
            ],
            [
                'id' => '93',
                'name' => 'magiër A t/m D',
                'cost' => '16',
                'manatype_id' => '1',
                'mana_amount' => '20',
                'sort_order' => '70',
                'deprecated' => '0',
            ],
            [
                'id' => '94',
                'name' => 'magiër A t/m E',
                'cost' => '20',
                'manatype_id' => '1',
                'mana_amount' => '25',
                'sort_order' => '70',
                'deprecated' => '0',
            ],
            [
                'id' => '95',
                'name' => 'magiër A t/m F',
                'cost' => '24',
                'manatype_id' => '1',
                'mana_amount' => '30',
                'sort_order' => '70',
                'deprecated' => '0',
            ],
            [
                'id' => '96',
                'name' => 'magiër A t/m G',
                'cost' => '28',
                'manatype_id' => '1',
                'mana_amount' => '35',
                'sort_order' => '70',
                'deprecated' => '0',
            ],
            [
                'id' => '97',
                'name' => 'magiër A t/m H',
                'cost' => '32',
                'manatype_id' => '1',
                'mana_amount' => '40',
                'sort_order' => '70',
                'deprecated' => '0',
            ],
            [
                'id' => '98',
                'name' => 'beschermer der elementen',
                'cost' => '4',
                'manatype_id' => '1',
                'mana_amount' => '5',
                'sort_order' => '71',
                'deprecated' => '0',
            ],
            [
                'id' => '99',
                'name' => 'beschermer der elementen x2',
                'cost' => '8',
                'manatype_id' => '1',
                'mana_amount' => '10',
                'sort_order' => '71',
                'deprecated' => '0',
            ],
            [
                'id' => '100',
                'name' => 'beschermer der elementen x3',
                'cost' => '12',
                'manatype_id' => '1',
                'mana_amount' => '15',
                'sort_order' => '71',
                'deprecated' => '0',
            ],
            [
                'id' => '101',
                'name' => 'glyphs vervaardigen (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '71',
                'deprecated' => '0',
            ],
            [
                'id' => '102',
                'name' => 'glyphs meesterschap (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '72',
                'deprecated' => '0',
            ],
            [
                'id' => '103',
                'name' => 'herken magisch voorwerp',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '72',
                'deprecated' => '0',
            ],
            [
                'id' => '104',
                'name' => 'spreuken in bepantsering',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '72',
                'deprecated' => '0',
            ],
            [
                'id' => '105',
                'name' => 'wapen der elementen A',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '72',
                'deprecated' => '0',
            ],
            [
                'id' => '106',
                'name' => 'wapen der elementen A t/m B',
                'cost' => '5',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '72',
                'deprecated' => '0',
            ],
            [
                'id' => '107',
                'name' => 'weef enchantment (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '72',
                'deprecated' => '0',
            ],
            [
                'id' => '108',
                'name' => 'weef enchantment x2 (lore)',
                'cost' => '4',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '72',
                'deprecated' => '0',
            ],
            [
                'id' => '109',
                'name' => 'weef enchantment x3 (lore)',
                'cost' => '6',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '72',
                'deprecated' => '0',
            ],
            [
                'id' => '110',
                'name' => 'weef enchantment x4 (lore)',
                'cost' => '8',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '72',
                'deprecated' => '0',
            ],
            [
                'id' => '111',
                'name' => 'necromantie A (genezer)',
                'cost' => '4',
                'manatype_id' => '3',
                'mana_amount' => '5',
                'sort_order' => '80',
                'deprecated' => '0',
            ],
            [
                'id' => '112',
                'name' => 'necromantie A t/m B (genezer)',
                'cost' => '8',
                'manatype_id' => '3',
                'mana_amount' => '10',
                'sort_order' => '80',
                'deprecated' => '0',
            ],
            [
                'id' => '113',
                'name' => 'necromantie A (magiër)',
                'cost' => '4',
                'manatype_id' => '1',
                'mana_amount' => '5',
                'sort_order' => '81',
                'deprecated' => '0',
            ],
            [
                'id' => '114',
                'name' => 'necromantie A t/m B (magiër)',
                'cost' => '8',
                'manatype_id' => '1',
                'mana_amount' => '10',
                'sort_order' => '81',
                'deprecated' => '0',
            ],
            [
                'id' => '115',
                'name' => 'necromantie A (priester)',
                'cost' => '4',
                'manatype_id' => '2',
                'mana_amount' => '5',
                'sort_order' => '82',
                'deprecated' => '0',
            ],
            [
                'id' => '116',
                'name' => 'necromantie A t/m B (priester)',
                'cost' => '8',
                'manatype_id' => '2',
                'mana_amount' => '10',
                'sort_order' => '82',
                'deprecated' => '0',
            ],
            [
                'id' => '117',
                'name' => 'animator',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '83',
                'deprecated' => '0',
            ],
            [
                'id' => '118',
                'name' => 'essentie overhevelen',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '83',
                'deprecated' => '0',
            ],
            [
                'id' => '119',
                'name' => 'priester A t/m D',
                'cost' => '16',
                'manatype_id' => '2',
                'mana_amount' => '20',
                'sort_order' => '90',
                'deprecated' => '0',
            ],
            [
                'id' => '120',
                'name' => 'priester A t/m E',
                'cost' => '20',
                'manatype_id' => '2',
                'mana_amount' => '25',
                'sort_order' => '90',
                'deprecated' => '0',
            ],
            [
                'id' => '121',
                'name' => 'priester A t/m F',
                'cost' => '24',
                'manatype_id' => '2',
                'mana_amount' => '30',
                'sort_order' => '90',
                'deprecated' => '0',
            ],
            [
                'id' => '122',
                'name' => 'priester A t/m G',
                'cost' => '28',
                'manatype_id' => '2',
                'mana_amount' => '35',
                'sort_order' => '90',
                'deprecated' => '0',
            ],
            [
                'id' => '123',
                'name' => 'priester A t/m H',
                'cost' => '32',
                'manatype_id' => '2',
                'mana_amount' => '40',
                'sort_order' => '90',
                'deprecated' => '0',
            ],
            [
                'id' => '124',
                'name' => 'dienaar van het geloof',
                'cost' => '4',
                'manatype_id' => '2',
                'mana_amount' => '5',
                'sort_order' => '91',
                'deprecated' => '0',
            ],
            [
                'id' => '125',
                'name' => 'herken spiritueel voorwerp',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '91',
                'deprecated' => '0',
            ],
            [
                'id' => '126',
                'name' => 'runen vervaardigen (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '91',
                'deprecated' => '0',
            ],
            [
                'id' => '127',
                'name' => 'runen meesterschap (lore & blanks)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '92',
                'deprecated' => '0',
            ],
            [
                'id' => '128',
                'name' => 'weef zegening (lore)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '92',
                'deprecated' => '0',
            ],
            [
                'id' => '129',
                'name' => 'weef zegening x2 (lore)',
                'cost' => '4',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '92',
                'deprecated' => '0',
            ],
            [
                'id' => '130',
                'name' => 'weef zegening x3 (lore)',
                'cost' => '6',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '92',
                'deprecated' => '0',
            ],
            [
                'id' => '131',
                'name' => 'weef zegening x4 (lore)',
                'cost' => '8',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '92',
                'deprecated' => '0',
            ],
            [
                'id' => '132',
                'name' => 'wreker A',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '92',
                'deprecated' => '0',
            ],
            [
                'id' => '133',
                'name' => 'wreker A t/m B',
                'cost' => '5',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '92',
                'deprecated' => '0',
            ],
            [
                'id' => '134',
                'name' => 'elementair ritualist 8',
                'cost' => '8',
                'manatype_id' => '4',
                'mana_amount' => '16',
                'sort_order' => '100',
                'deprecated' => '0',
            ],
            [
                'id' => '135',
                'name' => 'elementair ritualist 9',
                'cost' => '9',
                'manatype_id' => '4',
                'mana_amount' => '18',
                'sort_order' => '100',
                'deprecated' => '0',
            ],
            [
                'id' => '136',
                'name' => 'elementair ritualist 10',
                'cost' => '10',
                'manatype_id' => '4',
                'mana_amount' => '20',
                'sort_order' => '101',
                'deprecated' => '0',
            ],
            [
                'id' => '137',
                'name' => 'elementair ritualist 11',
                'cost' => '11',
                'manatype_id' => '4',
                'mana_amount' => '22',
                'sort_order' => '101',
                'deprecated' => '0',
            ],
            [
                'id' => '138',
                'name' => 'elementair ritualist 12',
                'cost' => '12',
                'manatype_id' => '4',
                'mana_amount' => '24',
                'sort_order' => '101',
                'deprecated' => '0',
            ],
            [
                'id' => '139',
                'name' => 'elementair ritualist 13',
                'cost' => '13',
                'manatype_id' => '4',
                'mana_amount' => '26',
                'sort_order' => '101',
                'deprecated' => '0',
            ],
            [
                'id' => '140',
                'name' => 'elementair ritualist 14',
                'cost' => '14',
                'manatype_id' => '4',
                'mana_amount' => '28',
                'sort_order' => '101',
                'deprecated' => '0',
            ],
            [
                'id' => '141',
                'name' => 'elementair ritualist 15',
                'cost' => '15',
                'manatype_id' => '4',
                'mana_amount' => '30',
                'sort_order' => '101',
                'deprecated' => '0',
            ],
            [
                'id' => '142',
                'name' => 'spiritueel ritualist 8',
                'cost' => '8',
                'manatype_id' => '5',
                'mana_amount' => '16',
                'sort_order' => '102',
                'deprecated' => '0',
            ],
            [
                'id' => '143',
                'name' => 'spiritueel ritualist 9',
                'cost' => '9',
                'manatype_id' => '5',
                'mana_amount' => '18',
                'sort_order' => '102',
                'deprecated' => '0',
            ],
            [
                'id' => '144',
                'name' => 'spiritueel ritualist 10',
                'cost' => '10',
                'manatype_id' => '5',
                'mana_amount' => '20',
                'sort_order' => '103',
                'deprecated' => '0',
            ],
            [
                'id' => '145',
                'name' => 'spiritueel ritualist 11',
                'cost' => '11',
                'manatype_id' => '5',
                'mana_amount' => '22',
                'sort_order' => '103',
                'deprecated' => '0',
            ],
            [
                'id' => '146',
                'name' => 'spiritueel ritualist 12',
                'cost' => '12',
                'manatype_id' => '5',
                'mana_amount' => '24',
                'sort_order' => '103',
                'deprecated' => '0',
            ],
            [
                'id' => '147',
                'name' => 'spiritueel ritualist 13',
                'cost' => '13',
                'manatype_id' => '5',
                'mana_amount' => '26',
                'sort_order' => '103',
                'deprecated' => '0',
            ],
            [
                'id' => '148',
                'name' => 'spiritueel ritualist 14',
                'cost' => '14',
                'manatype_id' => '5',
                'mana_amount' => '28',
                'sort_order' => '103',
                'deprecated' => '0',
            ],
            [
                'id' => '149',
                'name' => 'spiritueel ritualist 15',
                'cost' => '15',
                'manatype_id' => '5',
                'mana_amount' => '30',
                'sort_order' => '103',
                'deprecated' => '0',
            ],
            [
                'id' => '150',
                'name' => 'barriere breken',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '104',
                'deprecated' => '0',
            ],
            [
                'id' => '151',
                'name' => 'cirkel trekken',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '104',
                'deprecated' => '0',
            ],
            [
                'id' => '152',
                'name' => 'energie omzetten',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '104',
                'deprecated' => '0',
            ],
            [
                'id' => '153',
                'name' => 'ritueel leider',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '104',
                'deprecated' => '0',
            ],
            [
                'id' => '154',
                'name' => 'terugkeer naar de cirkel',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '104',
                'deprecated' => '0',
            ],
            [
                'id' => '155',
                'name' => 'gehardheid',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '156',
                'name' => 'gehardheid x2',
                'cost' => '6',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '157',
                'name' => 'hart van een krijger',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '158',
                'name' => 'kracht',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '159',
                'name' => 'macht A',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '160',
                'name' => 'macht A t/m B',
                'cost' => '4',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '161',
                'name' => 'mentale discipline',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '162',
                'name' => 'mentale gehardheid',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '163',
                'name' => 'pantser stapelen',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '164',
                'name' => 'precisie',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '165',
                'name' => 'splijten',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '166',
                'name' => 'wapenexpertise',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '110',
                'deprecated' => '0',
            ],
            [
                'id' => '167',
                'name' => 'berserk (vervalt)',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '168',
                'name' => 'berserk kracht (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '169',
                'name' => 'berserk macht (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '170',
                'name' => 'berserk mighty blow (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '171',
                'name' => 'blinde woede (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '172',
                'name' => 'brew greater potion (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '173',
                'name' => 'demonologie (vervalt)',
                'cost' => '5',
                'manatype_id' => '6',
                'mana_amount' => '10',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '174',
                'name' => 'dier aanhalen (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '175',
                'name' => 'drankjes brouwen A (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '176',
                'name' => 'drankjes brouwen B (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '177',
                'name' => 'evaluate (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '178',
                'name' => 'geestuitdrijving (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '179',
                'name' => 'genezing (vervalt)',
                'cost' => '7',
                'manatype_id' => '3',
                'mana_amount' => '10',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '180',
                'name' => 'genezing 7+1 (vervalt)',
                'cost' => '8',
                'manatype_id' => '3',
                'mana_amount' => '12',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '181',
                'name' => 'genezing 7+2 (vervalt)',
                'cost' => '9',
                'manatype_id' => '3',
                'mana_amount' => '14',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '182',
                'name' => 'genezing 7+3 (vervalt)',
                'cost' => '10',
                'manatype_id' => '3',
                'mana_amount' => '16',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '183',
                'name' => 'genezing 7+4 (vervalt)',
                'cost' => '11',
                'manatype_id' => '3',
                'mana_amount' => '18',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '184',
                'name' => 'genezing 7+5 (vervalt)',
                'cost' => '12',
                'manatype_id' => '3',
                'mana_amount' => '20',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '185',
                'name' => 'genezing 7+6 (vervalt)',
                'cost' => '13',
                'manatype_id' => '3',
                'mana_amount' => '22',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '186',
                'name' => 'genezing 7+7 (vervalt)',
                'cost' => '14',
                'manatype_id' => '3',
                'mana_amount' => '24',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '187',
                'name' => 'genezing 7+8 (vervalt)',
                'cost' => '15',
                'manatype_id' => '3',
                'mana_amount' => '26',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '188',
                'name' => 'giffen brouwen A (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '189',
                'name' => 'giffen brouwen B (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '190',
                'name' => 'imbue bandages (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '191',
                'name' => 'kameleon (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '192',
                'name' => 'levenskracht x2 (vervalt)',
                'cost' => '10',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '193',
                'name' => 'levenskracht x3 (vervalt)',
                'cost' => '15',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '194',
                'name' => 'levenskracht x4 (vervalt)',
                'cost' => '20',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '195',
                'name' => 'macht (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '196',
                'name' => 'magierspreuken in bepantsering (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '197',
                'name' => 'magierspreuken in bepantsering 2x (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '198',
                'name' => 'magierspreuken in bepantsering 3x (vervalt)',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '199',
                'name' => 'mighty blow (vervalt)',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '200',
                'name' => 'necromantie (vervalt)',
                'cost' => '5',
                'manatype_id' => '6',
                'mana_amount' => '10',
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '201',
                'name' => 'night vision (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '202',
                'name' => 'picklocks (5 marbles) (vervalt)',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '203',
                'name' => 'picklocks (6 marbles) (vervalt)',
                'cost' => '4',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '204',
                'name' => 'picklocks (7 marbles) (vervalt)',
                'cost' => '5',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '205',
                'name' => 'picklocks (8 marbles) (vervalt)',
                'cost' => '6',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '206',
                'name' => 'priesterlijke expertise (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '207',
                'name' => 'priesterlijke expertise 2x (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '208',
                'name' => 'priesterlijke expertise 3x (vervalt)',
                'cost' => '3',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '209',
                'name' => 'servitar uitdrijving (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '210',
                'name' => 'speak with animals (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '211',
                'name' => 'spreuk: discern diseases or affliction (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '212',
                'name' => 'spreuk: life draw (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '213',
                'name' => 'spreuk: protection from diseases (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '214',
                'name' => 'spreuk: purify body (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '215',
                'name' => 'spreuk: total healing (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '216',
                'name' => 'tracking (vervalt)',
                'cost' => '1',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '217',
                'name' => 'vrij van angst (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
            [
                'id' => '218',
                'name' => 'waar geloof (vervalt)',
                'cost' => '2',
                'manatype_id' => null,
                'mana_amount' => null,
                'sort_order' => '200',
                'deprecated' => '1',
            ],
        ];

        $table = $this->table('skills');
        $table->insert($data)->save();
    }
}
